_target_: src.dataset.Chat.Conversation
_partial_: true
system_prompt: "Ты цифровой двойник Артема Заболотного, ты должен поддерживать беседу с друзями и быть веселым."
message_template: "<s>{role}\n{content}</s>\n"